### ISSUE TITLE
ModuleNotFoundError on Python 3.13

### ISSUE THREAD

**Issue by LyricLy** [synodriver/python-bz3#12]
```py
>>> import bz3
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import bz3
  File "/home/lyricly/.local/lib/python3.13/site-packages/bz3/__init__.py", line 6, in <module>
    from bz3.backends import (
    ...<8 lines>...
    )
  File "/home/lyricly/.local/lib/python3.13/site-packages/bz3/backends/__init__.py", line 21, in <module>
    from bz3.backends.cython import (
    ...<12 lines>...
    )
  File "/home/lyricly/.local/lib/python3.13/site-packages/bz3/backends/cython/__init__.py", line 4, in <module>
    from bz3.backends.cython._bz3 import (
    ...<12 lines>...
    )
ModuleNotFoundError: No module named 'bz3.backends.cython._bz3'
```

**Comment by synodriver** [comment]
Sorry for the late reply. I think that is because I didn't compile it in the ci, I'm still waiting for cffi to support 313t(freethreading), so I can release a version in 3.13(both normal build and freethreading), otherwise the whole CI will fail. If you need it now, you can compile it from source, it's very easy with a C compiler.

**Comment by synodriver** [comment]
Ok. It fails as my [expected](https://github.com/synodriver/python-bz3/actions/runs/12852046862/job/35833538723)
